version: "3.8"

services:
  pong-server:
    image: "node:18-alpine"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: "npm run dev"
